### ISSUE TITLE
อำเภอ ID มันไม่ Match กับ ตัว ตำบลรึเปล่าครับ

### ISSUE THREAD

**Issue by ak3dkung** [kongvut/thai-province-data#1]
เหมือนว่า อำเภอ ID จริง กับ ที่อยู่ในไฟล์ tombons.json มัน match กันไม่ได้อ่ะคับ

**Comment by kongvut** [comment]
แก้ไข foreignKey ของตำบล (amphure_id) #[618f957](https://github.com/kongvut/thai-province-data/commit/618f957b0270aa260a81a92336d0672c7135abdd)
