### ISSUE TITLE
Why not spelled "Amphoe" instead of "Amphure"

### ISSUE THREAD

**Issue by klinsc** [kongvut/thai-province-data#18]
The correct spelling of "อำเภอ" in English should be "Amphoe," right?
As mentioned in https://en.wikipedia.org/wiki/Districts_of_Thailand.
Also, I am available to help contribute a pull request.

**Comment by kongvut** [comment]
Thank you for the good suggestion.

I still have no idea about this. I think it might be a spelling mistake.

But I have plans to update the wording to be more universal as below.

![](https://raw.githubusercontent.com/kongvut/thai-province-data/master/diagram.png)

- thai_amphures -> thai_districts
- thai_tambons -> thai_sub_districts
- thai_tambons.amphure_id -> thai_sub_districts->district_id

There will be update in next version and the addition of latitude, longitude.

**Comment by klinsc** [comment]
> Thank you for the good suggestion.
> 
> I still have no idea about this. I think it might be a spelling mistake.
> 
> But I have plans to update the wording to be more universal as below.
> 
> ![](https://raw.githubusercontent.com/kongvut/thai-province-data/master/diagram.png)
> 
> * thai_amphures -> thai_districts
> * thai_tambons -> thai_sub_districts
> * thai_tambons.amphure_id -> thai_sub_districts->district_id
> 
> There will be update in next version and the addition of latitude, longitude.

Nice to hear that!
Cheers🍻
