### ISSUE TITLE
ข้อมูลตำบลใน api_province_with_amphure_tambon.json ไม่มี field zip_code ครับ

### ISSUE THREAD

**Issue by winswahwah** [kongvut/thai-province-data#2]
ข้อมูลตำบลจาก
https://raw.githubusercontent.com/kongvut/thai-province-data/master/api_province_with_amphure_tambon.json
ไม่มี field zip_code ครับ สามารถช่วยเพิ่มให้ได้ไหมครับ ขอบคุณมากครับ

**Comment by kongvut** [comment]
> ข้อมูลตำบลจาก https://raw.githubusercontent.com/kongvut/thai-province-data/master/api_province_with_amphure_tambon.json ไม่มี field zip_code ครับ สามารถช่วยเพิ่มให้ได้ไหมครับ ขอบคุณมากครับ

#[b966829](https://github.com/kongvut/thai-province-data/commit/b966829d1eedd15772a803b3372adb30797a840d)
ขอบคุณที่แจ้งปัญหา เพิ่มข้อมูลให้เรียบร้อยแล้วนะครับ

- (ทั้งหมด) https://raw.githubusercontent.com/kongvut/thai-province-data/master/api_province_with_amphure_tambon.json

#[06ff389](https://github.com/kongvut/thai-province-data/commit/06ff389deb0c50dbd4a263685e61eedc47b1d52c)
แถมแบบย้อนกลับเพิ่มให้อีกอันโดยใช้ Tambon เป็นข้อมูลตั้งต้นครับ

(ทั้งหมด แบบย้อนกลับ) https://raw.githubusercontent.com/kongvut/thai-province-data/master/api_revert_tambon_with_amphure_province.json
