### ISSUE TITLE
ข้อมูลชื่ออำเภอผิดครับ

### ISSUE THREAD

**Issue by snorlack** [kongvut/thai-province-data#3]
{
"id": 3315,
"name_th": "น้ำเกลี้ยง",
"name_en": "Si Rattana",
"province_id": 22,
"created_at": "2019-08-09T03:33:09.000+07:00",
"updated_at": "2022-05-16T06:31:26.606+07:00",
"deleted_at": null,
"tambon": [...]
}

**Comment by kongvut** [comment]
หมายถึงชื่อ eng ใช่ไหมครับ ควรเป็น Nam Kliang หรือเปล่าครับ

**Comment by snorlack** [comment]
ใช่แล้วครับ
